services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/node/nodebase
    container_name: ${NOMBRE}
    ports:
      - "3000:80"   
    env_file:
      - ./.env
    image: francisco/nodejs
    volumes:
      - ./logs:/root/logs      
  