services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/nginx/nginxbase
    container_name: ${NOMBRE}
    ports:
      - "8081:80"     
    env_file:
      - ./.env
    image: francisco/nginx
    volumes:
      - ./logs:/root/logs      
    networks:
      practicanginx:
        ipv4_address: ${IP}
networks:
  practicanginx:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}