services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/nginx/nginxbase
    container_name: ${NOMBRE}
    ports:
      - "80:80"     
    env_file:
      - ./.env
    image: francisco/nginx
    volumes:
      - ./logs:/root/logs      
